version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /data/db:/data/db:rw

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - ./current/public:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - ./vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - "nginx-proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost:/etc/nginx/vhost.d
      - ./current/public:/usr/share/nginx/html

  eventclient:
    build: octopus-frontend
    environment:
      VIRTUAL_HOST: event.abcer.world
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: event.abcer.world
      LETSENCRYPT_EMAIL: shu@abcer.world

  urlservice:
    build: urlservice
    environment:
      VIRTUAL_HOST: u.abcer.world
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: u.abcer.world
      LETSENCRYPT_EMAIL: shu@abcer.world

  eventserver:
    build: octopus-backend
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      VIRTUAL_HOST: api.abcer.world
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: api.abcer.world
      LETSENCRYPT_EMAIL: shu@abcer.world
      SECRET: 'event.abcer.world'
    volumes:
      - ./octopus-backend:/data

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  octopus-backend:
